version: "3.8"

services:
  webserver:
    build: .
    ports:
      - "80:8080"
    volumes:
      - ./uploads:/app/uploads
      - ./index.html:/app/index.html
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
